written = [
    "cat.rs",
    "cluster.rs",
    "dangling_indices.rs",
    "indices.rs",
    "ingest.rs",
    "nodes.rs",
    "remote_store.rs",
    "root/mod.rs",
    "search_pipeline.rs",
    "snapshot.rs",
    "tasks.rs",
]
merged = [
    "lib.rs",
    "params.rs",
]
